[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$major.$minor.$patch$prerelease"
version = "3.0.4"
version_files = [
    "package.json:version",
    "ios/Plugin/CapacitorUpdater.swift",
    "android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdater.java",
    "package.json:version",
    ".cz.toml"
]
